// svelte/src/App.svelte
<script>
  import { getPatientInfo, onPatientChanged } from '@arrowhealth/bridge-sdk'

  const state = { patient: null }

  getPatientInfo().then((patient) => (state.patient = patient))

  onPatientChanged((patient) => (state.patient = patient))
</script>

<main>
  <h2>Bridge Starter (Svelte)</h2>
  <strong>PATIENT INFO</strong>
  <pre><code>{JSON.stringify(state.patient, null, 2)}</code></pre>
</main>

<style>
  :root {
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    color: #2c3e50;
    margin-top: 10px;
  }
</style>

// emulator/src/App.vue
<script setup lang="ts">
import Boundaries from './components/Boundaries.vue';
import Controls from './components/Controls.vue';
</script>

<template>
  <Boundaries />
  <Controls />
</template>

<style>
#app {
  position: relative;
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
</style>
