// react/src/App.jsx
import { Component } from 'react'
import { getPatientInfo, onPatientChanged } from '@arrowhealth/bridge-sdk'
import './App.css'

class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      patient: {},
    }
  }

  async componentDidMount() {
    // check if patient is currently in view on initialization
    const patientInfo = await getPatientInfo()
    this.setState({ patient: patientInfo })

    // listen for changes while application is open
    onPatientChanged((patientInfo) => this.setState({ patient: patientInfo }))
  }

  render() {
    return (
      <div>
        <h2>Bridge Starter (React)</h2>
        <strong>PATIENT INFO</strong>
        <pre>
          <code>{JSON.stringify(this.state.patient, null, 2)}</code>
        </pre>
      </div>
    )
  }
}

export default App

// vue/src/App.vue
<script setup>
import { onMounted, ref } from 'vue';
import * as bridge from '@arrowhealth/bridge-sdk'

const patient = ref({})
const session

onMounted(async () => {
  patient.value = await bridge.getPatientInfo()
  bridge.onPatientChanged(patientInfo => patient.value = patientInfo)
})
</script>

<template>
  <h2>Bridge Starter (Vue)</h2>
  <strong>PATIENT INFO</strong>
  <pre><code>{{JSON.stringify(patient, null, 2)}}</code></pre>
</template>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
  margin-top: 10px;
}
</style>
